services:
  database:
    image: 'postgres:17'
    container_name: statistics_container
    ports:
    - '5432:5432'
    environment:
      POSTGRES_USER: stefan
      POSTGRES_DB: statistics_gateway_db
      POSTGRES_PASSWORD: 1234
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - database

  redis:
    image: 'redis:latest'
    container_name: redis_cache_1
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: stefan
      REDIS_PASSWORD: password

volumes:
  postgres_data:



